export const pages: {
    id: number,
    title: string,
    content: string,
    isPublic: boolean,
    indexInTutorial: number
}[] = [{
    id: 1,
    title: "Riguardo Cubing Italy",
    content: "<h3 style=\"text-align:justify;\">Cos’è Cubing Italy?</h3><p style=\"text-align:justify;\">Cubing Italy è l’insieme di tutti i possessori di una WCA ID che partecipano regolarmente a competizioni sul territorio italiano. La WCA ID è una sigla personale che viene assegnata dopo aver partecipato alla prima competizione ufficiale WCA: essa è utilizzata per identificare in modo rapido ed univoco i risultati di un partecipante all’interno del database della WCA. Dunque, ricapitolando, se hai partecipato ad una competizione ufficiale WCA in Italia, allora sei un membro di Cubing Italy. Complimenti!</p><h3 style=\"text-align:justify;\">Qual è il nostro obiettivo?</h3><p style=\"text-align:justify;\">Cubing Italy si colloca all’interno della WCA, la World Cube Association, e ne fa sua la missione: diffondere lo speedcubing attraverso l’organizzazione di sempre più competizioni ufficiali e la partecipazione a dimostrazioni, fiere ed eventi simili.</p><h3 style=\"text-align:justify;\">Chi sono i delegati italiani WCA?</h3><p style=\"text-align:justify;\">I delegati italiani WCA sono quattro: Lorenzo Vigani Poli (dal 2009), Matteo Provasi (dal 2014), Gianluca Placenti (dal 2015) e Simone Cantarelli (dal 2017). La figura del delegato è fondamentale per lo svolgimento di una competizione ufficiale WCA, egli infatti, con la sua presenza, assicura che il regolamento WCA venga applicato e che la competizione sia ufficiale.</p>",
    isPublic: true,
    indexInTutorial: -1
},
{
    id: 2,
    title: "Tutorial",
    content: "<p>In questa pagina trovi un elenco di tutorial redatti dal Team Qualità di Cubing Italy.</p><p>In caso volessi segnalare un errore o richiedere un nuovo tutorial puoi <a href=\"mailto:cubingitaly@gmail.com\">inviarci un'e-mail</a>.</p>",
    isPublic: true,
    indexInTutorial: -1
},
{ id: 3, title: "Effettua l'accesso", content: "<p style=\"text-align:justify;\">Effettua il login utilizzando il tuo account WCA.</p><p style=\"text-align:justify;\"><strong>PRIVACY POLICY -</strong> Facendo login tramite l'account WCA, acconsentite alla archiviazione di informazioni personali (nome, WCAID) nel nostro Database, esclusivamente allo scopo di erogazione del servizio (pubblicazione e gestione degli articoli, tutorial ecc.). - Cubing Italy utilizza dei cookie tecnici che sono necessari alla normale erogazione del servizio. Tali cookie, che sono piccoli file di testo che vengono scaricati nei file temporanei del tuo browser, sono usati per memorizzare la propria sessione.</p>", isPublic: true, indexInTutorial: -1 },
{ id: 4, title: "Competizioni proposte", content: "<p style=\"text-align:justify;\">Nel seguente foglio si possono trovare le competizioni proposte per il prossimo semestre.</p><p style=\"text-align:justify;\">Il fatto che una competizione sia stata proposta non implica che si svolgerà sicuramente e sia le date che gli eventi sono variabili e potrebbero cambiare senza preavviso. Questa pagina viene resa disponibile per gli eventuali organizzatori in modo da arginare il rischio di organizzare più di una competizione nella stessa zona nello stesso periodo.</p><p style=\"text-align:justify;\">Se sei interessato a organizzare una competizione<a href=\"https://www.cubingitaly.org/tutorial/come-organizzare-una-competizione\"> leggi il tutorial su come organizzare una competizione</a>.</p>", isPublic: true, indexInTutorial: -1 },
{ id: 5, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 6, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 7, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 8, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 9, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 10, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 11, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 12, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 13, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 14, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 15, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 16, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 17, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 18, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 19, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 20, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 21, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 22, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 23, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 24, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 25, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 26, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 27, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 28, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 29, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 30, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 31, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 32, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 33, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 34, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 35, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 36, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 37, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 38, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 39, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 40, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 41, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 42, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 43, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 44, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 45, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 46, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 47, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 48, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 49, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 50, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 51, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 52, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 53, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 54, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 55, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 56, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 57, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 58, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 59, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 60, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 61, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 62, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 63, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 64, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 65, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 66, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 67, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 68, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 69, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 70, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 71, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 72, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 73, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 74, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 75, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 76, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 77, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 78, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 79, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 80, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 81, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 82, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 83, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 84, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 85, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 86, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 87, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 88, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 89, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 90, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 91, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 92, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 93, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 94, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 95, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 96, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 97, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 98, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 99, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 },
{ id: 100, title: "Reserved", content: "Reserved", isPublic: false, indexInTutorial: -1 }
    ]
